name: Exploring workflows Triggers

on: 
  workflow_dispatch:
  push:
  #schedule:
  #  - cron: "*/2 * * * *"   # <=== Change this value
env:
    CONTAINER_REGISTRY: docker.io
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    IMAGE_NAME: gh-ac-nginx
    DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN}}
jobs:
    Docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/$DOCKERHUB_USERNAME/$IMAGE_NAME:latest
          
        - name: Docker login
          run: echo docker login --username=DOCKERHUB_USERNAME --password=$DOCKER_PASSWORD
          
        - name: Docker Image Publish
          run: echo docker push $CONTAINER_REGISTRY/$DOCKERHUB_USERNAME/$IMAGE_NAME:latest
        
        #- name: Login to Docker Hub
        #  uses: docker/login-action@v3
        #  with:
        #    username: ${{ secrets.DOCKERHUB_USERNAME}}
        #    password: ${{ secrets.DOCKERHUB_TOKEN}}
            
    Deploy:
        if: github.ref == 'ref/heads/main'
        needs: Docker
        runs-on: ubuntu-latest
        concurrency:
          group: production-deployment
          cancel-in-progress: false
        steps:
        - name: Docker Run
          timeout-minutes: 1
          run: |
            echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKERHUB_USERNAME/$IMAGE_NAME:latest
            sleep 69s
