name: Exploring Workflow filters and activities
on: 
  push:
    #branch-ignores:
    #  - feature/*
    #  - test/**
    branches:
      - main
      - '!feature/*'
  workflow_dispatch:
  #schedule:
  #  - cron: "*/59 * * * *"
  pull:
  pull-request:
    types:
      - opened
      - closed
    paths-ignore:
      - README.md
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo this workflow/jobs/step is executed for event type - ${{ github.event_name }}