name: Exploring Variables and Secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: arj007
    IMAGE_NAME: gh-ac-nginx
jobs:
    Docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/$DOCKERHUB_USERNAME/$IMAGE_NAME:latest
          
        - name: Docker login
          env:
            DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN}}
          run: echo docker login --username=DOCKERHUB_USERNAME --password=$DOCKER_PASSWORD
          
        - name: Docker Image Publish
          env:
            DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN}}
            DOCKER_USERNAME: arj007
          run: echo docker push $CONTAINER_REGISTRY/$DOCKERHUB_USERNAME/$IMAGE_NAME:latest
        
        #- name: Login to Docker Hub
        #  uses: docker/login-action@v3
        #  with:
        #    username: ${{ secrets.DOCKERHUB_USERNAME}}
        #    password: ${{ secrets.DOCKERHUB_TOKEN}}
            
    Deploy:
        needs: Docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKERHUB_USERNAME/$IMAGE_NAME:latest

