name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: Welcome Message with listing of current directory Files
          run: |
            echo "Preparing for GitHub Actions Certification"
            ls -ltra
            cat README.md
            
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a dragon....RAAW" >> dragon.txt