name: Generate ASCII ArtWork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: Install Cosway Program
          run: sudo apt-get install cowsay -y
          
        - name: Execute Cosway CMD
          run: cowsay -f dragon "Run for cover, I am a dragon....RAAW" >> dragon.txt
          
        - name: Test File Exists Status
          run: grep -i "dragon" dragon.txt
            
        - name: Read File
          run: cat dragon.txt
          
        - name: List Repo Files
          run: ls -ltra
